name: CI Test

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Check code formatting with black
      run: |
        black --check .
    - name: Typecheck with mypy
      run: |
        mypy .
    - name: Test with pytest
      run: |
        pytest tests
